### ISSUE TITLE
Opening charts from direct command never completes

### ISSUE THREAD

**Issue by logikonabstractions** [simulogics/prosperousuniverse-docs#54]
# Issue - to reproduce

- Open a new Buffer on any screen
- Enter a complete command to obtain the charts for a specific commodity on a specific exchange. For example: `cxpc si.nc1`
- The buffer keeps loads the command, but apparently never completes (on the left):
![image](https://user-images.githubusercontent.com/46571570/207733212-9ea54255-57d8-443a-9dc0-34252df00f08.png)

However, if one goes to the same chart by going through the exchange and clicking one's way to the same chart, it loads fine in the buffer (as seen on the right - the chart was obtain by going through the Moria Station Exchange --> Metals --> Silicon and then clicking on the chart in that buffer).

* I don't know if you guys intend some process to report UI/in-game issues but I just thought opening an issue on git wasn't a bad way to go on about it.  **

**Comment by molp** [comment]
Thanks for the bug report. We usually use the forums to report bugs, either in [this topic](https://com.prosperousuniverse.com/t/bugs-and-improvements/151) or the [feedback category](https://com.prosperousuniverse.com/c/feedback/10).

The issue here is, that some commands do not work when written in lower case. Try `CXPC SI.NC1` instead. This is a known issue and we have yet to fix it. I am thus going to close this.
